### ISSUE TITLE
Keyboard Input

### ISSUE THREAD

**Issue by tgodfrey0** [inventor02/curdle#5]

**Comment by inventor02** [comment]
@a-caine please can you take a look at this?

With Kindest Regards,

Regards,
George

**Comment by a-caine** [comment]
Dear @inventor02 ,

I am currently working on this issue as of now.

Regards,
Adam

**Comment by a-caine** [comment]
Dear @inventor02,

I believe I have resolved this issue. 
Please feel free re-open if you believe the issue has still not been fully resolved.

Kindest regards,
Adam
