### ISSUE TITLE
game_init discards the constant qualifier from pointer

### ISSUE THREAD

**Issue by a-caine** [inventor02/curdle#6]
Dear @inventor02 ,

Could you please take a look at this issue? It is currently giving me warning every time I compile.

Kindest Regards,
Adam

**Comment by inventor02** [comment]
Hi Adam,

I’ll investigate this evening

With Kindest Regards,
George

**Comment by tgodfrey0** [comment]
Hi @a-caine and @inventor02,

I have sorted this issue and the warnings have been resolved.

Regards, 
Toby
